// Java Program for the game.
import java.util.Scanner;

public class NGG {

	// Function for the number guessing game
	public static void NumberGame(){
		
		Scanner sc = new Scanner(System.in);

		// Random number generated by system
		int number = 1 + (int)(100 * Math.random());          //Math.random() method returns a pseudorandom double type number
		                                                      //  greater than or equal to 0.0 and less than 1.0.

		// K attempts
		int K = 5;

		int i, guessNum;

		System.out.println("INSTRUCTIONS : ");
		System.out.println("A number is chosen randomly from 1 to 100 by the Computer.");
		System.out.println("You have to guess the number right to win the game. You will be given 5 attempts.");
		System.out.println("Lets get started !!");
		System.out.println();
		System.out.println("Guess the number:");

		// Iterate over K Attempts
		for (i = 0; i < K; i++) {

			System.out.print((i+1) + " Attempt : ");

			// Take input from user for guessing
			guessNum = sc.nextInt();

			// Cases
			if (number == guessNum) {
				System.out.println("Congratulations!! You guessed the number.");
				System.out.println("You Won!!");
				break;
			}

			else if ((number > guessNum ) && (i != K - 1)) {
				System.out.println("The number is greater than " + guessNum);
			}

			else if ((number < guessNum) && (i != K - 1)) {
				System.out.println("The number is less than " + guessNum);
			}
		}

		if (i == K) {
			System.out.println("You have exhausted all of your attempts.");
            System.out.println("You lose!!");
			System.out.println("The number was " + number);
		}
	}

	public static void main(String arg[])
	{
		// Function Call
		NumberGame();
	}
}
